### ISSUE TITLE
Make compatible for Laravel 6 (and 7)

### ISSUE THREAD

**Issue by ben221199** [tenantcloud/laravel-boolean-softdeletes#3]
## Detailed description

I use Laravel 6, but because this library is made for Laravel 5.1, I cannot use it.

## Context

I use Laravel 6. Other people that use Laravel 6 can use the library too then.

## Your environment

 - PHP 7.1
 - Windows 10

**Comment by YaroslavNahirnyi** [comment]
Already implemented
